'use client';

import { useState } from 'react';
import { createTeamTask, updateTeamTask } from '../actions';

// ---------------------------------------------------------------------------
// Constants — kept in sync with the server-side page.tsx
// ---------------------------------------------------------------------------

const EQUIPMENT_OPTIONS = [
  'PPE',
  'Aircraft stands',
  'Safety signs',
  'Safety raiser',
  'Ladders',
  'Tie-downs',
  'Cherry picker',
  'Tow vehicle',
] as const;

const CONSUMABLE_OPTIONS = ['Paint', 'Brushes', 'Oils/greases', 'Tape'] as const;

const SAFETY_OPTIONS = [
  'Working at height',
  'Public presence',
  'Mains electricity',
  'Heavy items',
  'Confined spaces',
  'COSHH (Chemicals)',
] as const;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type TaskData = {
  id: string;
  teamId: string;
  title: string;
  taskType: 'SITE' | 'DISPLAY' | 'AIRFRAME';
  urgency: 'ROUTINE' | 'MODERATE' | 'URGENT';
  description: string | null;
  personnelRequired: number | null;
  supervisorRequired: boolean;
  equipment: string[];
  equipmentOther: string | null;
  consumables: string[];
  consumablesOther: string | null;
  safetyIssues: string[];
  safetyIssuesOther: string | null;
  equipmentLocations: string | null;
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Generate a locations template from selected equipment and consumables.
 * Preserves any existing value already entered for each item (key: value format).
 */
function buildTemplate(
  equipment: string[],
  equipmentOther: string,
  consumables: string[],
  consumablesOther: string,
  existing: string,
): string {
  const items = [
    ...equipment,
    ...(equipmentOther.trim() ? [equipmentOther.trim()] : []),
    ...consumables,
    ...(consumablesOther.trim() ? [consumablesOther.trim()] : []),
  ];

  if (items.length === 0) return '';

  // Parse the existing text to preserve known values
  const preserved = new Map<string, string>();
  existing.split('\n').forEach((line) => {
    const colonIdx = line.indexOf(':');
    if (colonIdx > 0) {
      preserved.set(line.slice(0, colonIdx).trim(), line.slice(colonIdx + 1).trim());
    }
  });

  return items.map((item) => `${item}: ${preserved.get(item) ?? ''}`).join('\n');
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export default function TaskFormClient({
  teams,
  task,
}: {
  teams: { id: string; name: string }[];
  task?: TaskData;
}) {
  const isEdit = !!task;

  // Controlled checkbox state (for auto-populate)
  const [equipment, setEquipment] = useState<string[]>(task?.equipment ?? []);
  const [equipmentOther, setEquipmentOther] = useState(task?.equipmentOther ?? '');
  const [consumables, setConsumables] = useState<string[]>(task?.consumables ?? []);
  const [consumablesOther, setConsumablesOther] = useState(task?.consumablesOther ?? '');
  const [safetyIssues, setSafetyIssues] = useState<string[]>(task?.safetyIssues ?? []);

  // Locations: tracks the textarea value; we detect if the user has manually
  // edited it so we don't silently overwrite their work on subsequent selection changes.
  const [locations, setLocations] = useState(task?.equipmentLocations ?? '');
  const [locationsAutoGenerated, setLocationsAutoGenerated] = useState(false);

  // Bound server action — createTeamTask needs only FormData; updateTeamTask needs taskId first
  const formAction = isEdit ? updateTeamTask.bind(null, task.id) : createTeamTask;

  // -------------------------------------------------------------------------
  // Auto-populate logic
  // -------------------------------------------------------------------------

  /** Called whenever a checkbox changes. Auto-populates locations if the field is
   *  empty or was previously auto-generated (i.e. the user hasn't manually edited it). */
  function syncLocations(
    nextEquipment: string[],
    nextEquipmentOther: string,
    nextConsumables: string[],
    nextConsumablesOther: string,
  ) {
    if (!locationsAutoGenerated && locations.trim() !== '') return; // user has own text — don't touch
    const template = buildTemplate(
      nextEquipment,
      nextEquipmentOther,
      nextConsumables,
      nextConsumablesOther,
      locations,
    );
    setLocations(template);
    setLocationsAutoGenerated(true);
  }

  function handleEquipmentChange(opt: string, checked: boolean) {
    const next = checked ? [...equipment, opt] : equipment.filter((e) => e !== opt);
    setEquipment(next);
    syncLocations(next, equipmentOther, consumables, consumablesOther);
  }

  function handleConsumablesChange(opt: string, checked: boolean) {
    const next = checked ? [...consumables, opt] : consumables.filter((c) => c !== opt);
    setConsumables(next);
    syncLocations(equipment, equipmentOther, next, consumablesOther);
  }

  function handleEquipmentOtherChange(val: string) {
    setEquipmentOther(val);
    syncLocations(equipment, val, consumables, consumablesOther);
  }

  function handleConsumablesOtherChange(val: string) {
    setConsumablesOther(val);
    syncLocations(equipment, equipmentOther, consumables, val);
  }

  function handleLocationsChange(val: string) {
    setLocations(val);
    setLocationsAutoGenerated(false); // user is now in control
  }

  /** Force-regenerate the template, preserving existing values. */
  function regenerateTemplate() {
    const template = buildTemplate(equipment, equipmentOther, consumables, consumablesOther, locations);
    setLocations(template);
    setLocationsAutoGenerated(true);
  }

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------

  return (
    <form action={formAction} className="space-y-6">
      {/* Team selection */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Team *</label>
          <select
            name="teamId"
            required
            defaultValue={task?.teamId ?? ''}
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">Select team…</option>
            {teams.map((t) => (
              <option key={t.id} value={t.id}>
                {t.name}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Task title * (max 200 chars)</label>
          <input
            name="title"
            type="text"
            required
            maxLength={200}
            defaultValue={task?.title ?? ''}
            placeholder="e.g. Aircraft exterior wash"
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      {/* Type and urgency */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Type *</label>
          <select
            name="taskType"
            required
            defaultValue={task?.taskType ?? 'SITE'}
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="SITE">Site</option>
            <option value="DISPLAY">Display</option>
            <option value="AIRFRAME">Airframe</option>
          </select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Urgency *</label>
          <select
            name="urgency"
            required
            defaultValue={task?.urgency ?? 'ROUTINE'}
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="ROUTINE">Routine</option>
            <option value="MODERATE">Moderate (deterioration)</option>
            <option value="URGENT">Urgent (safety)</option>
          </select>
        </div>
      </div>

      {/* Description */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Task description (max 3000 chars)</label>
        <textarea
          name="description"
          rows={3}
          maxLength={3000}
          defaultValue={task?.description ?? ''}
          placeholder="Free-text description of the task…"
          className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y"
        />
      </div>

      {/* Personnel and supervisor */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Expected number of personnel required
          </label>
          <input
            name="personnelRequired"
            type="number"
            min={1}
            max={999}
            defaultValue={task?.personnelRequired ?? ''}
            placeholder="e.g. 4"
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <div className="flex items-center gap-3 pt-6">
          <input
            id={`supervisor-${task?.id ?? 'new'}`}
            name="supervisorRequired"
            type="checkbox"
            value="1"
            defaultChecked={task?.supervisorRequired ?? false}
            className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
          />
          <label htmlFor={`supervisor-${task?.id ?? 'new'}`} className="text-sm text-gray-700">
            Does supervisor need to be present?
          </label>
        </div>
      </div>

      {/* Equipment required */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">Equipment required</label>
        <div className="flex flex-wrap gap-3">
          {EQUIPMENT_OPTIONS.map((opt) => (
            <label key={opt} className="flex items-center gap-1.5 text-sm text-gray-700 cursor-pointer">
              <input
                type="checkbox"
                name="equipment"
                value={opt}
                checked={equipment.includes(opt)}
                onChange={(e) => handleEquipmentChange(opt, e.target.checked)}
                className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
              />
              {opt}
            </label>
          ))}
        </div>
        <div className="mt-2">
          <input
            type="text"
            name="equipmentOther"
            maxLength={200}
            value={equipmentOther}
            onChange={(e) => handleEquipmentOtherChange(e.target.value)}
            placeholder="Add other equipment…"
            className="border border-gray-200 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 w-full sm:w-72"
          />
        </div>
      </div>

      {/* Consumables */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">Consumables</label>
        <div className="flex flex-wrap gap-3">
          {CONSUMABLE_OPTIONS.map((opt) => (
            <label key={opt} className="flex items-center gap-1.5 text-sm text-gray-700 cursor-pointer">
              <input
                type="checkbox"
                name="consumables"
                value={opt}
                checked={consumables.includes(opt)}
                onChange={(e) => handleConsumablesChange(opt, e.target.checked)}
                className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
              />
              {opt}
            </label>
          ))}
        </div>
        <div className="mt-2">
          <input
            type="text"
            name="consumablesOther"
            maxLength={200}
            value={consumablesOther}
            onChange={(e) => handleConsumablesOtherChange(e.target.value)}
            placeholder="Add other consumable…"
            className="border border-gray-200 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 w-full sm:w-72"
          />
        </div>
      </div>

      {/* Safety issues */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">Safety issues</label>
        <div className="flex flex-wrap gap-3">
          {SAFETY_OPTIONS.map((opt) => (
            <label key={opt} className="flex items-center gap-1.5 text-sm text-gray-700 cursor-pointer">
              <input
                type="checkbox"
                name="safetyIssues"
                value={opt}
                checked={safetyIssues.includes(opt)}
                onChange={(e) =>
                  setSafetyIssues(
                    e.target.checked
                      ? [...safetyIssues, opt]
                      : safetyIssues.filter((s) => s !== opt),
                  )
                }
                className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
              />
              {opt}
            </label>
          ))}
        </div>
        <div className="mt-2">
          <input
            type="text"
            name="safetyIssuesOther"
            maxLength={200}
            defaultValue={task?.safetyIssuesOther ?? ''}
            placeholder="Add other safety issue…"
            className="border border-gray-200 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 w-full sm:w-72"
          />
        </div>
      </div>

      {/* Equipment locations — auto-populated from selections */}
      <div>
        <div className="flex items-center justify-between mb-1">
          <label className="block text-sm font-medium text-gray-700">
            Where to find the selected equipment / consumables
          </label>
          <button
            type="button"
            onClick={regenerateTemplate}
            className="text-xs text-blue-600 hover:underline"
          >
            ↺ Regenerate from selections
          </button>
        </div>
        <p className="text-xs text-gray-400 mb-1">
          Auto-populates when you tick equipment or consumables. Edit freely — your changes are preserved.
        </p>
        <textarea
          name="equipmentLocations"
          rows={Math.max(3, (equipment.length + consumables.length + 1))}
          maxLength={5000}
          value={locations}
          onChange={(e) => handleLocationsChange(e.target.value)}
          placeholder="e.g. PPE: Red cabinet at hangar entrance&#10;Ladders: Store room, shelf B"
          className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y font-mono"
        />
        <p className="text-xs text-gray-400 mt-0.5 text-right">{locations.length} / 5000</p>
      </div>

      <div className="pt-2">
        <button
          type="submit"
          className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2.5 rounded-lg text-sm font-medium transition-colors"
        >
          {isEdit ? 'Save changes' : 'Create task'}
        </button>
      </div>
    </form>
  );
}
