/** Canonical list of all capabilities in the system. */
export const CAPABILITIES = [
  { key: 'admin:users.read', description: 'View all users' },
  { key: 'admin:users.write', description: 'Create, update, delete users' },
  { key: 'admin:roles.read', description: 'View roles and capabilities' },
  { key: 'admin:roles.write', description: 'Create, update, delete roles' },
  { key: 'admin:teams.read', description: 'View teams' },
  { key: 'admin:teams.write', description: 'Create, update, delete teams' },
  { key: 'admin:tasks.write', description: 'Create and manage team tasks' },
  { key: 'admin:audit.read', description: 'View audit logs' },
  { key: 'admin:files.read', description: 'View all uploaded files' },
  { key: 'admin:files.write', description: 'Upload and manage files' },
  { key: 'admin:announcements.write', description: 'Create and manage announcements' },
  { key: 'admin:calendar.write', description: 'Create and manage calendar events and jobs' },
  { key: 'admin:act-as.write', description: 'Manage schedules and availability on behalf of others' },
  { key: 'admin:museum.write', description: 'Edit museum status, opening hours, and bank holidays' },
  { key: 'admin:settings.write', description: 'Manage system settings (SMTP, etc.) — root only' },
  { key: 'admin:theme.write', description: 'Manage site theme and settings' },
  { key: 'admin:training.write', description: 'Create and manage training policies' },
  { key: 'staff:volunteer.read', description: 'View all volunteers and their availability' },
  { key: 'staff:projects.read', description: 'View upcoming projects and team assignments' },
  { key: 'staff:messaging.write', description: 'Send messages to individuals or groups' },
  { key: 'staff:schedule.read', description: 'View full schedule and availability' },
  { key: 'volunteer:tasks.read', description: 'View tasks' },
  { key: 'volunteer:tasks.write', description: 'Create and update tasks' },
] as const;
